### ISSUE TITLE
Getting an assertion error trying to run effect_demo.py

### ISSUE THREAD

**Issue by KenwoodFox** [axlan/opencv_effects#1]
```
python effect_demo.py
Traceback (most recent call last):
  File "/tmp/python_cv_temp/effect_demo.py", line 174, in <module>
    main()
  File "/tmp/python_cv_temp/effect_demo.py", line 150, in main
    laughing_face_effect.process_frame(frame)
  File "/tmp/python_cv_temp/effect_demo.py", line 60, in process_frame
    faces = self.faceCascade.detectMultiScale(
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-_i61028x/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'
```

Im getting the above error, anything stand out? Python 3.9.5

**Comment by axlan** [comment]
It seems like the file `haarcascade_frontalface_default.xml` might not be being loaded. 

If you add:
```
import os
print(os.path.exists('haarcascade_frontalface_default.xml'))
exit()
```
to the script does it print `true`?
